PYTHON = python
VIEWER = less

.PHONY: prob1 run view

prob1 : prob1.py
	chmod u+x prob1.py
	$(PYTHON) prob1.py

run :	prob1.py
	chmod u+x prob1.py
	$(PYTHON) prob1.py
	
view : prob1.py
	$(VIEWER) prob1.py